import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { pool } from '../db.js';
import {
  authMiddleware,
  requireRole,
  privacyReacceptanceGate,
  tosReacceptanceGate,
  type AuthedRequest,
} from '../auth.js';

// Issue #1032 — per-tenant branded report export templates, applied to the
// regulatory state-report and compliance report downloads. Template changes
// only affect presentation metadata (logo/header/footer) attached to an
// export — the underlying report data is computed identically either way.
export const reportTemplatesRouter = Router();
reportTemplatesRouter.use(authMiddleware);
reportTemplatesRouter.use(privacyReacceptanceGate);
reportTemplatesRouter.use(tosReacceptanceGate);
reportTemplatesRouter.use(requireRole('surety_admin'));

export interface ReportTemplate {
  logoUrl: string | null;
  headerText: string | null;
  footerText: string | null;
}

export const DEFAULT_REPORT_TEMPLATE: ReportTemplate = {
  logoUrl: null,
  headerText: 'TariffShield Compliance Report',
  footerText: 'Generated by TariffShield — confidential, for regulatory use only.',
};

interface ReportTemplateRow {
  logo_url: string | null;
  header_text: string | null;
  footer_text: string | null;
}

export async function getReportTemplate(suretyId: string): Promise<ReportTemplate> {
  const row = await pool.query<ReportTemplateRow>(
    `SELECT logo_url, header_text, footer_text FROM report_templates WHERE surety_id = $1`,
    [suretyId]
  );
  if (row.rowCount === 0) return DEFAULT_REPORT_TEMPLATE;
  const r = row.rows[0]!;
  return {
    logoUrl: r.logo_url ?? DEFAULT_REPORT_TEMPLATE.logoUrl,
    headerText: r.header_text ?? DEFAULT_REPORT_TEMPLATE.headerText,
    footerText: r.footer_text ?? DEFAULT_REPORT_TEMPLATE.footerText,
  };
}

const TemplateSchema = z.object({
  logoUrl: z.string().url().max(2000).nullable().optional(),
  headerText: z.string().max(200).nullable().optional(),
  footerText: z.string().max(400).nullable().optional(),
});

// GET /report-templates — current tenant's saved template, falling back to the default.
reportTemplatesRouter.get('/', async (req: Request, res: Response) => {
  const user = (req as AuthedRequest).user;
  const template = await getReportTemplate(user.id);
  res.json({ template, isDefault: template === DEFAULT_REPORT_TEMPLATE });
});

// PUT /report-templates — upsert the tenant's template.
reportTemplatesRouter.put('/', async (req: Request, res: Response) => {
  const user = (req as AuthedRequest).user;

  const parse = TemplateSchema.safeParse(req.body);
  if (!parse.success) {
    res.status(400).json({ error: 'invalid template fields', details: parse.error.issues });
    return;
  }

  const { logoUrl, headerText, footerText } = parse.data;

  const result = await pool.query(
    `INSERT INTO report_templates (surety_id, logo_url, header_text, footer_text)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (surety_id) DO UPDATE
       SET logo_url = $2, header_text = $3, footer_text = $4, updated_at = now()
     RETURNING logo_url, header_text, footer_text`,
    [user.id, logoUrl ?? null, headerText ?? null, footerText ?? null]
  );

  const row = result.rows[0]!;
  res.json({
    template: { logoUrl: row.logo_url, headerText: row.header_text, footerText: row.footer_text },
  });
});
