'use client';

import { useEffect, useState } from 'react';
import { api, type ReportTemplate } from '@/lib/api';

// Issue #1032 — per-tenant branded export template settings (logo,
// header, footer) applied to the regulatory/compliance report downloads.
// Saving never touches the underlying report data.
export function ReportTemplateEditor() {
  const [saved, setSaved] = useState<ReportTemplate | null>(null);
  const [draft, setDraft] = useState<ReportTemplate>({
    logoUrl: null,
    headerText: null,
    footerText: null,
  });
  const [showPreview, setShowPreview] = useState(false);
  const [status, setStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  useEffect(() => {
    api
      .getReportTemplate()
      .then((r) => {
        setSaved(r.template);
        setDraft(r.template);
      })
      .catch(() => setStatus('error'));
  }, []);

  async function handleSave() {
    setStatus('saving');
    try {
      const r = await api.saveReportTemplate(draft);
      setSaved(r.template);
      setStatus('saved');
      window.setTimeout(() => setStatus('idle'), 2000);
    } catch {
      setStatus('error');
    }
  }

  const field = (
    key: keyof ReportTemplate,
    label: string,
    placeholder: string,
    maxLength: number
  ) => (
    <label className="block">
      <span className="block text-xs text-muted">{label}</span>
      <input
        type="text"
        value={draft[key] ?? ''}
        maxLength={maxLength}
        onChange={(e) => setDraft((d) => ({ ...d, [key]: e.target.value || null }))}
        placeholder={placeholder}
        className="mt-1 w-full rounded-md border border-border bg-background px-2 py-1.5 text-sm focus:border-accent focus:outline-none"
      />
    </label>
  );

  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <h3 className="text-sm font-semibold">Branded report export template</h3>
      <p className="mt-1 text-xs text-muted">
        Applied to regulatory state-report and compliance report downloads. Falls back to the
        default template when unset. {saved === null ? 'Loading…' : null}
      </p>

      <div className="mt-3 space-y-3">
        {field('logoUrl', 'Logo URL', 'https://example.com/logo.png', 2000)}
        {field('headerText', 'Header text', 'TariffShield Compliance Report', 200)}
        {field('footerText', 'Footer text', 'Confidential — for regulatory use only.', 400)}
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => setShowPreview(true)}
          className="rounded-md border border-border px-3 py-1.5 text-xs hover:bg-background"
        >
          Preview
        </button>
        <button
          type="button"
          onClick={handleSave}
          disabled={status === 'saving'}
          className="rounded-md bg-accent text-accent-foreground px-3 py-1.5 text-xs hover:opacity-90 disabled:opacity-50"
        >
          {status === 'saving' ? 'Saving…' : 'Save template'}
        </button>
        {status === 'saved' && <span className="text-xs text-success">Saved</span>}
        {status === 'error' && <span className="text-xs text-danger">Something went wrong</span>}
      </div>

      {showPreview && (
        <div className="mt-4 rounded-md border border-dashed border-border bg-background p-3 text-xs">
          <p className="text-[10px] uppercase tracking-wide text-muted">Preview (not saved)</p>
          {draft.logoUrl ? (
            <p className="mt-1 text-muted font-mono break-all">{draft.logoUrl}</p>
          ) : null}
          <p className="mt-1 font-semibold">
            {draft.headerText || 'TariffShield Compliance Report'}
          </p>
          <p className="mt-2 text-muted">State Compliance Report — sample data, not saved</p>
          <p className="mt-2 text-muted italic">
            {draft.footerText ||
              'Generated by TariffShield — confidential, for regulatory use only.'}
          </p>
        </div>
      )}
    </div>
  );
}
